<?php

require_once '../app/require.php';
require_once '../app/controllers/AdminController.php';

$user = new UserController();
$admin = new AdminController();

Session::init();

include '../includes/db.php';

$username = Session::get("username");

$invList = $admin->getInvCodeArray();

Util::adminCheck();
Util::head('Admin Panel');
Util::navbar();

// if post request
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST["genInv"])) {
        $admin->getInvCodeGen($username);
        $sql = "INSERT INTO `logs` (`log_user`, `log_action`, `log_time`) VALUES ('$username', 'Generated Invite Code', NOW())";
        $result = $mysqli->query($sql);

        //
        $webhook = INVITE_WEBHOOK;
        $embed = array(
            "title" => "New Invite Code",
            "description" => "A new invite code has been generated by $username",
            "color" => 0x00ff00
        );
        $data = array(
            "embeds" => array($embed)
        );
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/json\r\n",
                'method'  => 'POST',
                'content' => json_encode($data)
            )
        );
        // send webhook
        $context  = stream_context_create($options);
        $result = file_get_contents($webhook, false, $context);
    }

    header("location: invites");

	if (isset($_POST["invWave"])) {

		$admin->getInvWaveGen($username);

        $webhook = INVITE_WEBHOOK;
        $embed = array(
            "title" => "New Invite Wave",
            "description" => "A new invite wave has been generated by $username",
            "color" => 0x00ff00
        );
        $data = array(
            "embeds" => array($embed)
        );
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/json\r\n",
                'method'  => 'POST',
                'content' => json_encode($data)
            )
        );
        // send webhook
        $context  = stream_context_create($options);
        $result = file_get_contents($webhook, false, $context);

    }

    header("location: invites");
}
?>

<div class="container mt-2">
	<div class="row">

		<?php Util::adminNavbar(); ?>

		<div class="col-12 mt-3">
			<div class="rounded p-3 mb-3">

				<form method="POST" action="<?php Util::display($_SERVER['PHP_SELF']); ?>">
								
					<button name="genInv" type="submit" class="btn btn-outline-primary btn-sm">
						Gen Code
					</button>

				</form>
			</div>
		</div>

		<div class="col-12 mb-2">
			<table class="rounded table">

				<thead>
					<tr>
						<th scope="col">Code</th>
						<th scope="col">Created By</th>
					</tr>
				</thead>
				<tbody>

					<?php foreach ($invList as $row) : ?>
						<tr>
							<td><?php Util::display($row->code); ?></td>
							<td><?php Util::display($row->createdBy); ?></td>
						</tr>
					<?php endforeach; ?>

				</tbody>

			</table>

		</div>
	</div>

</div>

<?php Util::footer(); ?>
